name: Backend
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  static:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: rollout
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: packages/@rollout/backend/package-lock.json

      - name: Install dependencies
        working-directory: ./packages/@rollout/backend
        run: npm install

      - name: Preparation
        working-directory: ./packages/@rollout/backend
        run: mv .env.example .env && npm run db:migrate:dev && npm run db:generate:schema

      - name: Build
        working-directory: ./packages/@rollout/backend
        run: npm run build

      - name: Lint
        working-directory: ./packages/@rollout/backend
        run: npm run lint

      - name: Tests
        working-directory: ./packages/@rollout/backend
        run: npm run test

      - name: API tests
        working-directory: ./packages/@rollout/backend
        run: npm run test:e2e
