name: Automated tests
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  static:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: packages/@rollout/backend/package-lock.json

      - name: Install dependencies
        working-directory: ./packages/@rollout/backend
        run: npm install

      - name: Run tests
        working-directory: ./packages/@rollout/backend
        run: npm run test

      - name: Run API tests
        working-directory: ./packages/@rollout/backend
        run: npm run test:e2e
