name: E2E
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  static:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            packages/@rollout/frontend/package-lock.json
            packages/@rollout/backend/package-lock.json

      - name: Creating .env files
        run: mv ./packages/@rollout/frontend/.env.example ./packages/@rollout/frontend/.env && mv ./packages/@rollout/backend/.env.example ./packages/@rollout/backend/.env

      - name: Install dependencies
        run: npm install

      - name: Bootstrap projects
        run: npm run setup

      - name: Prepare sqlite DB
        run: npm run db:prepare:sqlite

      - name: Build
        run: npm run build

      - name: Start the backend project
        working-directory: ./packages/@rollout/backend
        run: npm start &

      - name: Start the frontend project
        working-directory: ./packages/@rollout/frontend
        run: npm start &

      - name: E2E tests
        run: npx wait-on -t 60000 tcp:4000 && npm run test:e2e:ci
